import _BBC_BLOCKS from './svgs/bbcBlocks';
import _BBC_BLOCKS_DARK_MODE from './svgs/bbcBlocksDarkMode';
import _coreIcons from './svgs/coreIcons';
import _mediaIcons from './svgs/mediaIcons';
import _navigationIcons from './svgs/navigationIcons';
import _afaanoromoo from './svgs/afaanoromoo';
import _afrique from './svgs/afrique';
import _amharic from './svgs/amharic';
import _arabic from './svgs/arabic';
import _archive from './svgs/archive';
import _azeri from './svgs/azeri';
import _bengali from './svgs/bengali';
import _burmese from './svgs/burmese';
import _cymrufyw from './svgs/cymrufyw';
import _gahuza from './svgs/gahuza';
import _gujarati from './svgs/gujarati';
import _hausa from './svgs/hausa';
import _hindi from './svgs/hindi';
import _igbo from './svgs/igbo';
import _indonesia from './svgs/indonesia';
import _japanese from './svgs/japanese';
import _korean from './svgs/korean';
import _kyrgyz from './svgs/kyrgyz';
import _learningenglish from './svgs/learningenglish';
import _marathi from './svgs/marathi';
import _mundo from './svgs/mundo';
import _naidheachdan from './svgs/naidheachdan';
import _nepali from './svgs/nepali';
import _news from './svgs/news';
import _newsround from './svgs/newsround';
import _pashto from './svgs/pashto';
import _persian from './svgs/persian';
import _pidgin from './svgs/pidgin';
import _portuguese from './svgs/portuguese';
import _punjabi from './svgs/punjabi';
import _russian from './svgs/russian';
import _scotland from './svgs/scotland';
import _serbian from './svgs/serbian';
import _sinhala from './svgs/sinhala';
import _somali from './svgs/somali';
import _sport from './svgs/sport';
import _swahili from './svgs/swahili';
import _tamil from './svgs/tamil';
import _telugu from './svgs/telugu';
import _thai from './svgs/thai';
import _tigrinya from './svgs/tigrinya';
import _turkce from './svgs/turkce';
import _urdu from './svgs/urdu';
import _ukchina from './svgs/ukchina';
import _ukrainian from './svgs/ukrainian';
import _uzbek from './svgs/uzbek';
import _vietnamese from './svgs/vietnamese';
import _weather from './svgs/weather';
import _yoruba from './svgs/yoruba';
import _zhongwen from './svgs/zhongwen';

export { _BBC_BLOCKS as BBC_BLOCKS };
export { _BBC_BLOCKS_DARK_MODE as BBC_BLOCKS_DARK_MODE };
export { _coreIcons as coreIcons };
export { _mediaIcons as mediaIcons };
export { _navigationIcons as navigationIcons };
export { _afaanoromoo as afaanoromoo };
export { _afrique as afrique };
export { _amharic as amharic };
export { _arabic as arabic };
export { _archive as archive };
export { _azeri as azeri };
export { _bengali as bengali };
export { _burmese as burmese };
export { _cymrufyw as cymrufyw };
export { _gahuza as gahuza };
export { _gujarati as gujarati };
export { _hausa as hausa };
export { _hindi as hindi };
export { _igbo as igbo };
export { _indonesia as indonesia };
export { _japanese as japanese };
export { _korean as korean };
export { _kyrgyz as kyrgyz };
export { _learningenglish as learningenglish };
export { _marathi as marathi };
export { _mundo as mundo };
export { _naidheachdan as naidheachdan };
export { _nepali as nepali };
export { _news as news };
export { _newsround as newsround };
export { _pashto as pashto };
export { _persian as persian };
export { _pidgin as pidgin };
export { _portuguese as portuguese };
export { _punjabi as punjabi };
export { _russian as russian };
export { _scotland as scotland };
export { _serbian as serbian };
export { _sinhala as sinhala };
export { _somali as somali };
export { _sport as sport };
export { _swahili as swahili };
export { _tamil as tamil };
export { _telugu as telugu };
export { _thai as thai };
export { _tigrinya as tigrinya };
export { _turkce as turkce };
export { _urdu as urdu };
export { _ukchina as ukchina };
export { _ukrainian as ukrainian };
export { _uzbek as uzbek };
export { _vietnamese as vietnamese };
export { _weather as weather };
export { _yoruba as yoruba };

export { _zhongwen as zhongwen };
